// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ClaudeDesktopSettingsService Claude Desktop 的 settings 四件套实现
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ApplySingleProvider 应用指定供应商：
 * - Direct：inferenceGatewayBaseUrl/ApiKey 直连供应商
 * - Proxy：指向本地代理（:18100 的 Claude 链路），Key 使用 app_settings 持久化的网关 token
 * - 官方条目（Category=="official"）：deploymentMode 写 1p 并清除 profile 自定义内容
 */
export function ApplySingleProvider(providerID: number): $CancellablePromise<void> {
    return $Call.ByID(280269704, providerID);
}

/**
 * GetStatus Claude Desktop 当前配置状态摘要（mode/baseUrl/供应商名）
 */
export function GetStatus(): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(1415428943).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ImportFromLive 首次接入：检测 3p profile 的网关配置并导入为供应商（导入后不修改原生文件）
 */
export function ImportFromLive(): $CancellablePromise<boolean> {
    return $Call.ByID(1839032548);
}

/**
 * ProxyStatus 检查当前 profile 是否指向本地代理（:18100 Claude 链路）
 */
export function ProxyStatus(): $CancellablePromise<$models.ClaudeDesktopProxyStatus | null> {
    return $Call.ByID(212872207).then(($result: any) => {
        return $$createType2($result);
    });
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $models.ClaudeDesktopProxyStatus.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
