// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetStatus(): $CancellablePromise<$models.ClaudeModelRoutingStatus> {
    return $Call.ByID(2655226325).then(($result: any) => {
        return $$createType0($result);
    });
}

export function HandleModelLibraryChanged(): $CancellablePromise<void> {
    return $Call.ByID(3057430085);
}

export function HandleProvidersChanged(previous: $models.Provider[], next: $models.Provider[]): $CancellablePromise<void> {
    return $Call.ByID(612326181, previous, next);
}

export function HandleSettingsChanged(previous: $models.AppSettings, next: $models.AppSettings): $CancellablePromise<void> {
    return $Call.ByID(2679256774, previous, next);
}

export function ListModels(limit: number, beforeID: string, afterID: string): $CancellablePromise<$models.ClaudeModelListResponse> {
    return $Call.ByID(2023635251, limit, beforeID, afterID).then(($result: any) => {
        return $$createType1($result);
    });
}

export function RefreshAll(): $CancellablePromise<$models.ClaudeModelRefreshResult> {
    return $Call.ByID(1269364275).then(($result: any) => {
        return $$createType2($result);
    });
}

export function ResolveProviders(requestedModel: string, providers: $models.Provider[]): $CancellablePromise<$models.Provider[]> {
    return $Call.ByID(2660350727, requestedModel, providers).then(($result: any) => {
        return $$createType4($result);
    });
}

export function Start(): $CancellablePromise<void> {
    return $Call.ByID(1657140003);
}

export function Stop(): $CancellablePromise<void> {
    return $Call.ByID(3569880881);
}

// Private type creation functions
const $$createType0 = $models.ClaudeModelRoutingStatus.createFrom;
const $$createType1 = $models.ClaudeModelListResponse.createFrom;
const $$createType2 = $models.ClaudeModelRefreshResult.createFrom;
const $$createType3 = $models.Provider.createFrom;
const $$createType4 = $Create.Array($$createType3);
