// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CodexOAuthService 管理 ChatGPT Codex OAuth 登录与 access token 刷新。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetStatus(): $CancellablePromise<$models.CodexOAuthStatus | null> {
    return $Call.ByID(3625114194).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetValidToken(accountID: string): $CancellablePromise<[string, string]> {
    return $Call.ByID(3405445991, accountID);
}

export function ListAccounts(): $CancellablePromise<$models.CodexOAuthAccount[]> {
    return $Call.ByID(2719649088).then(($result: any) => {
        return $$createType3($result);
    });
}

export function Logout(): $CancellablePromise<void> {
    return $Call.ByID(1262882186);
}

export function PollLogin(deviceCode: string): $CancellablePromise<$models.CodexOAuthAccount | null> {
    return $Call.ByID(4087412926, deviceCode).then(($result: any) => {
        return $$createType4($result);
    });
}

export function RemoveAccount(accountID: string): $CancellablePromise<void> {
    return $Call.ByID(1869165067, accountID);
}

export function SetDefaultAccount(accountID: string): $CancellablePromise<void> {
    return $Call.ByID(1943223056, accountID);
}

export function Start(): $CancellablePromise<void> {
    return $Call.ByID(3305530520);
}

export function StartLogin(): $CancellablePromise<$models.CodexOAuthDeviceCodeResponse | null> {
    return $Call.ByID(1997741013).then(($result: any) => {
        return $$createType6($result);
    });
}

export function Stop(): $CancellablePromise<void> {
    return $Call.ByID(3226524988);
}

// Private type creation functions
const $$createType0 = $models.CodexOAuthStatus.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.CodexOAuthAccount.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Nullable($$createType2);
const $$createType5 = $models.CodexOAuthDeviceCodeResponse.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
