// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * GrokSettingsService Grok Build 的 settings 四件套实现
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ApplySingleProvider 直连应用指定供应商：替换 config.toml 的模型配置节
 * provider.ConfigTOML 为该供应商的 TOML 片段（[model.<profile>] + [models].default）；
 * 其余顶层键（如 mcp_servers）保留；空 TOML 即回到官方态（清空模型节）
 */
export function ApplySingleProvider(providerID: number): $CancellablePromise<void> {
    return $Call.ByID(2451231201, providerID);
}

/**
 * DisableProxy 关闭代理：优先从备份恢复接管前的直连配置；
 * 备份缺失且当前确为代理态时，清除 live 的 model/models 节回到未配置态，
 * 让用户可以重新应用供应商（解除「无备份 → 无法关闭 → 无法切换」的死锁）
 */
export function DisableProxy(): $CancellablePromise<void> {
    return $Call.ByID(4217099648);
}

/**
 * EnableProxy 代理接管：备份当前 config.toml 后，将选中 profile 指向本地代理
 * 仅替换 base_url / api_key，api_backend 保留用户原值（空时才写默认 responses），
 * 其余顶层键（如 mcp_servers）原样保留；已处于代理态时幂等返回
 */
export function EnableProxy(): $CancellablePromise<void> {
    return $Call.ByID(3094857581);
}

/**
 * GetStatus Grok 当前配置状态摘要
 */
export function GetStatus(): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(208465042).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ImportFromLive 首次接入：检测 ~/.grok/config.toml 的自定义模型表并导入为供应商
 * 仅导入非官方态的选中 profile；导入后不修改原生文件
 */
export function ImportFromLive(): $CancellablePromise<boolean> {
    return $Call.ByID(1326288803);
}

/**
 * ProxyStatus 检查 Grok 是否处于代理接管状态（选中 profile 的 base_url 指向本地代理）
 */
export function ProxyStatus(): $CancellablePromise<$models.GrokProxyStatus | null> {
    return $Call.ByID(3333471182).then(($result: any) => {
        return $$createType2($result);
    });
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $models.GrokProxyStatus.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
