// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * HermesService Hermes 配置服务（additive 共存模式：全部条目共存于 custom_providers，切换 = 更新顶层 model 节）
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddProvider 新增供应商并追加 live 条目（ID 缺省生成 hermes-<unixnano>）
 * live 冲突守卫：目标 ID 已存在于 custom_providers 时拒绝，需先走导入纳入管理
 * 返回落库后的完整供应商（含生成的 ID），供前端精确回填
 */
export function AddProvider(provider: $models.HermesProvider): $CancellablePromise<$models.HermesProvider> {
    return $Call.ByID(1610946238, provider).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * DeleteProvider 删除供应商（同步移除 live 条目）
 */
export function DeleteProvider(id: string): $CancellablePromise<void> {
    return $Call.ByID(4120323630, id);
}

/**
 * DuplicateProvider 复制供应商（副本默认未启用，生成新 ID）
 */
export function DuplicateProvider(sourceID: string): $CancellablePromise<$models.HermesProvider | null> {
    return $Call.ByID(778202060, sourceID).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetMemoryContent 读取 memory 整文件内容（kind: "memory" | "user"；文件缺失返回空串）
 */
export function GetMemoryContent(kind: string): $CancellablePromise<string> {
    return $Call.ByID(291595252, kind);
}

/**
 * GetMemoryEntries 读取 memory 条目列表（按单独一行的 § 切分，空白条目过滤）
 */
export function GetMemoryEntries(kind: string): $CancellablePromise<string[]> {
    return $Call.ByID(2503677697, kind).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetMemorySettings 读取 memory 开关与字符预算（缺键回退默认值）
 */
export function GetMemorySettings(): $CancellablePromise<$models.HermesMemorySettings | null> {
    return $Call.ByID(3128371774).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * GetProviders 获取全部供应商（统一存储视图）
 */
export function GetProviders(): $CancellablePromise<$models.HermesProvider[]> {
    return $Call.ByID(2195267354).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * GetStatus live 配置状态摘要（configExists / providers 数 / 当前启用）
 */
export function GetStatus(): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(3255767602).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * ImportFromLive 导入 live custom_providers 的全部条目为供应商（导入后不修改原生文件）
 */
export function ImportFromLive(): $CancellablePromise<number> {
    return $Call.ByID(2122643459);
}

/**
 * SetCurrentProvider 切换语义：custom_providers 条目全部共存保留 + 顶层 model 节指向该供应商
 * model 节写为 map 结构（{provider: <name>, model: <model>}，model 为空时省略 model 键）
 */
export function SetCurrentProvider(id: string): $CancellablePromise<void> {
    return $Call.ByID(1774304416, id);
}

/**
 * SetMemorySettings 写入 memory 开关与字符预算（config.yaml 顶层四键，其余键保留）
 */
export function SetMemorySettings(enabled: boolean, charLimit: number, userEnabled: boolean, userCharLimit: number): $CancellablePromise<void> {
    return $Call.ByID(2310951058, enabled, charLimit, userEnabled, userCharLimit);
}

export function Start(): $CancellablePromise<void> {
    return $Call.ByID(1933932856);
}

export function Stop(): $CancellablePromise<void> {
    return $Call.ByID(3011200604);
}

/**
 * UpdateProvider 更新供应商（live 条目整体替换为最新字段），返回更新后的完整供应商
 */
export function UpdateProvider(provider: $models.HermesProvider): $CancellablePromise<$models.HermesProvider> {
    return $Call.ByID(305092684, provider).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * WriteMemoryContent 原子写入 memory 整文件内容（Markdown blob，调用方负责 § 分隔符拼接）
 */
export function WriteMemoryContent(kind: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(2565664169, kind, content);
}

// Private type creation functions
const $$createType0 = $models.HermesProvider.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = $models.HermesMemorySettings.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = $Create.Array($$createType0);
const $$createType6 = $Create.Map($Create.Any, $Create.Any);
