// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as modelpricing$0 from "../resources/model-pricing/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function BindClaudeModelRoutingService(routing: $models.ClaudeModelRoutingService | null): $CancellablePromise<void> {
    return $Call.ByID(449398538, routing);
}

export function DeleteModelPricing(model: string): $CancellablePromise<void> {
    return $Call.ByID(3910206009, model);
}

export function ListModelPricing(): $CancellablePromise<$models.ModelPricingRow[]> {
    return $Call.ByID(1319106306).then(($result: any) => {
        return $$createType1($result);
    });
}

export function PreviewClaudeOfficialPricing(): $CancellablePromise<$models.ClaudeOfficialPricingPreviewResult> {
    return $Call.ByID(287628864).then(($result: any) => {
        return $$createType2($result);
    });
}

export function PreviewCloudPriceTableSyncConflicts(): $CancellablePromise<$models.CloudPriceTableSyncConflictResult> {
    return $Call.ByID(1522473657).then(($result: any) => {
        return $$createType3($result);
    });
}

export function Service(): $CancellablePromise<modelpricing$0.Service | null> {
    return $Call.ByID(3226590882).then(($result: any) => {
        return $$createType5($result);
    });
}

export function SyncClaudeOfficialPricing(): $CancellablePromise<$models.ModelPricingSyncResult> {
    return $Call.ByID(1550361071).then(($result: any) => {
        return $$createType6($result);
    });
}

export function SyncCloudPriceTable(overwriteManualModels: string[]): $CancellablePromise<$models.ModelPricingSyncResult> {
    return $Call.ByID(1643878514, overwriteManualModels).then(($result: any) => {
        return $$createType6($result);
    });
}

export function UpsertModelPricing(row: $models.ModelPricingRow): $CancellablePromise<void> {
    return $Call.ByID(147781953, row);
}

// Private type creation functions
const $$createType0 = $models.ModelPricingRow.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.ClaudeOfficialPricingPreviewResult.createFrom;
const $$createType3 = $models.CloudPriceTableSyncConflictResult.createFrom;
const $$createType4 = modelpricing$0.Service.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $models.ModelPricingSyncResult.createFrom;
