// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * OpenClawService OpenClaw 配置服务（additive 共存模式：所有条目共存于原生配置，切换 = 标记启用）
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddProvider 新增供应商并写入 live 条目（ID 缺省生成 openclaw-<unixnano>）
 * live 冲突守卫：目标 ID 已存在于 live 时拒绝，需先走导入纳入管理
 * 返回落库后的完整供应商（含生成的 ID），供前端精确回填
 */
export function AddProvider(provider: $models.OpenClawProvider): $CancellablePromise<$models.OpenClawProvider> {
    return $Call.ByID(1778448529, provider).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * DeleteProvider 删除供应商（同步移除 live 条目）
 */
export function DeleteProvider(id: string): $CancellablePromise<void> {
    return $Call.ByID(2906212919, id);
}

/**
 * DuplicateProvider 复制供应商（副本默认未启用，生成新 ID）
 */
export function DuplicateProvider(sourceID: string): $CancellablePromise<$models.OpenClawProvider | null> {
    return $Call.ByID(1918415587, sourceID).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetAgentsConfig 读取顶层 agents.defaults（内部结构透传，前端编辑）
 */
export function GetAgentsConfig(): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(2198478303).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetEnvConfig 读取顶层 env 节的 vars / shellEnv
 */
export function GetEnvConfig(): $CancellablePromise<$models.OpenClawEnvConfig | null> {
    return $Call.ByID(4254516996).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * GetProviders 获取全部供应商（统一存储视图）
 */
export function GetProviders(): $CancellablePromise<$models.OpenClawProvider[]> {
    return $Call.ByID(317460127).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * GetStatus live 配置状态摘要（settingsPath / configExists / providers 数 / 当前启用）
 */
export function GetStatus(): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(318687249).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetToolsConfig 读取顶层 tools 节（profile / allow / deny）
 */
export function GetToolsConfig(): $CancellablePromise<$models.OpenClawToolsConfig | null> {
    return $Call.ByID(3644616384).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * ImportFromLive 导入 live models.providers 的全部条目为供应商（导入后不修改原生文件）
 */
export function ImportFromLive(): $CancellablePromise<number> {
    return $Call.ByID(484002086);
}

/**
 * SetAgentsConfig 写入顶层 agents.defaults（只改 agents 键，保留其他顶层键）
 */
export function SetAgentsConfig(defaults: { [_ in string]?: any }): $CancellablePromise<void> {
    return $Call.ByID(1199368251, defaults);
}

/**
 * SetCurrentProvider 切换语义：写 live 该条目（additive 共存，其余条目保留）+ 统一存储单选标记
 */
export function SetCurrentProvider(id: string): $CancellablePromise<void> {
    return $Call.ByID(1101129001, id);
}

/**
 * SetEnvConfig 写入顶层 env 节（只改 env 键，保留 models/tools/agents 等其他顶层键）
 */
export function SetEnvConfig(vars: { [_ in string]?: string }, shellEnv: { [_ in string]?: string }): $CancellablePromise<void> {
    return $Call.ByID(931562256, vars, shellEnv);
}

/**
 * SetToolsConfig 写入顶层 tools 节（profile 限 minimal/coding/messaging/full）
 */
export function SetToolsConfig(profile: string, allow: string[], deny: string[]): $CancellablePromise<void> {
    return $Call.ByID(170875844, profile, allow, deny);
}

export function Start(): $CancellablePromise<void> {
    return $Call.ByID(350353135);
}

export function Stop(): $CancellablePromise<void> {
    return $Call.ByID(2569271861);
}

/**
 * UpdateProvider 更新供应商（live 条目整体替换为最新字段），返回更新后的完整供应商
 */
export function UpdateProvider(provider: $models.OpenClawProvider): $CancellablePromise<$models.OpenClawProvider> {
    return $Call.ByID(2411158609, provider).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $models.OpenClawProvider.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
const $$createType3 = $models.OpenClawEnvConfig.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = $Create.Array($$createType0);
const $$createType6 = $models.OpenClawToolsConfig.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
