// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * OpenCodeService OpenCode 配置管理服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

const $$SERVICE_PATH = "codeswitch/services.OpenCodeService";

export function AddProvider(provider: $models.OpenCodeProvider): $CancellablePromise<void> {
    return $Call.ByName(`${$$SERVICE_PATH}.AddProvider`, provider);
}

export function DeleteProvider(id: string): $CancellablePromise<void> {
    return $Call.ByName(`${$$SERVICE_PATH}.DeleteProvider`, id);
}

export function DuplicateProvider(sourceID: string): $CancellablePromise<$models.OpenCodeProvider | null> {
    return $Call.ByName(`${$$SERVICE_PATH}.DuplicateProvider`, sourceID).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetPresets(): $CancellablePromise<$models.OpenCodeProviderPreset[]> {
    return $Call.ByName(`${$$SERVICE_PATH}.GetPresets`).then(($result: any) => {
        return $$createType3($result);
    });
}

export function GetProviders(): $CancellablePromise<$models.OpenCodeProvider[]> {
    return $Call.ByName(`${$$SERVICE_PATH}.GetProviders`).then(($result: any) => {
        return $$createType4($result);
    });
}

export function GetLiveProviderIds(): $CancellablePromise<string[]> {
    return $Call.ByName(`${$$SERVICE_PATH}.GetLiveProviderIds`).then(($result: any) => {
        return Array.isArray($result) ? $result.map(($item: any) => String($item)) : [];
    });
}

export function ImportFromLive(): $CancellablePromise<number> {
    return $Call.ByName(`${$$SERVICE_PATH}.ImportFromLive`);
}

export function ReorderProviders(ids: string[]): $CancellablePromise<void> {
    return $Call.ByName(`${$$SERVICE_PATH}.ReorderProviders`, ids);
}

export function SaveProviders(providers: $models.OpenCodeProvider[]): $CancellablePromise<void> {
    return $Call.ByName(`${$$SERVICE_PATH}.SaveProviders`, providers);
}

export function Start(): $CancellablePromise<void> {
    return $Call.ByName(`${$$SERVICE_PATH}.Start`);
}

export function Stop(): $CancellablePromise<void> {
    return $Call.ByName(`${$$SERVICE_PATH}.Stop`);
}

export function UpdateProvider(provider: $models.OpenCodeProvider): $CancellablePromise<void> {
    return $Call.ByName(`${$$SERVICE_PATH}.UpdateProvider`, provider);
}

// Private type creation functions
const $$createType0 = $models.OpenCodeProvider.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.OpenCodeProviderPreset.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Array($$createType0);
