// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AddProvider(provider: $models.OpenCodeProvider): $CancellablePromise<void> {
    return $Call.ByID(1696168747, provider);
}

export function DeleteProvider(id: string): $CancellablePromise<void> {
    return $Call.ByID(1181751877, id);
}

export function DuplicateProvider(sourceID: string): $CancellablePromise<$models.OpenCodeProvider | null> {
    return $Call.ByID(3164262841, sourceID).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetLiveProviderIds(): $CancellablePromise<string[]> {
    return $Call.ByID(1965663488).then(($result: any) => {
        return $$createType2($result);
    });
}

export function GetPresets(): $CancellablePromise<$models.OpenCodeProviderPreset[]> {
    return $Call.ByID(498048199).then(($result: any) => {
        return $$createType4($result);
    });
}

export function GetProviders(): $CancellablePromise<$models.OpenCodeProvider[]> {
    return $Call.ByID(3464978189).then(($result: any) => {
        return $$createType5($result);
    });
}

export function ImportFromLive(): $CancellablePromise<number> {
    return $Call.ByID(2924384212);
}

export function ReorderProviders(ids: string[]): $CancellablePromise<void> {
    return $Call.ByID(2206345732, ids);
}

export function SaveProviders(providers: $models.OpenCodeProvider[]): $CancellablePromise<void> {
    return $Call.ByID(3563048736, providers);
}

export function Start(): $CancellablePromise<void> {
    return $Call.ByID(1833019225);
}

export function Stop(): $CancellablePromise<void> {
    return $Call.ByID(3833518131);
}

export function UpdateProvider(provider: $models.OpenCodeProvider): $CancellablePromise<void> {
    return $Call.ByID(2592411031, provider);
}

// Private type creation functions
const $$createType0 = $models.OpenCodeProvider.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = $models.OpenCodeProviderPreset.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $Create.Array($$createType0);
