// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PiService Pi 配置服务（additive 共存模式：所有条目共存于原生配置，切换 = 标记启用）
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddProvider 新增供应商并写入 live 条目（ID 缺省生成 pi-<unixnano>）
 * live 冲突守卫：目标 ID 已存在于 live providers 时拒绝，需先走导入纳入管理
 * 返回落库后的完整供应商（含生成的 ID），供前端精确回填
 */
export function AddProvider(provider: $models.PiProvider): $CancellablePromise<$models.PiProvider> {
    return $Call.ByID(3919023165, provider).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * DeleteProvider 删除供应商（同步移除 live 条目）
 */
export function DeleteProvider(id: string): $CancellablePromise<void> {
    return $Call.ByID(1315457723, id);
}

/**
 * DuplicateProvider 复制供应商（副本默认未启用，生成新 ID）
 */
export function DuplicateProvider(sourceID: string): $CancellablePromise<$models.PiProvider | null> {
    return $Call.ByID(115241687, sourceID).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetProviders 获取全部供应商（统一存储视图）
 */
export function GetProviders(): $CancellablePromise<$models.PiProvider[]> {
    return $Call.ByID(1355408027).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetStatus live 配置状态摘要（configExists / providers 数 / 当前启用）
 */
export function GetStatus(): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(2619481549).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * ImportFromLive 导入 live providers 的全部条目为供应商（导入后不修改原生文件）
 */
export function ImportFromLive(): $CancellablePromise<number> {
    return $Call.ByID(532062546);
}

/**
 * SetCurrentProvider 切换语义：models.json 的 providers 无全局 default 概念，
 * 仅统一存储单选标记 + 同步 live 托管子树（全部条目共存保留）
 */
export function SetCurrentProvider(id: string): $CancellablePromise<void> {
    return $Call.ByID(3362540989, id);
}

export function Start(): $CancellablePromise<void> {
    return $Call.ByID(3795579451);
}

export function Stop(): $CancellablePromise<void> {
    return $Call.ByID(2742329577);
}

/**
 * UpdateProvider 更新供应商（live 条目整体替换为最新字段），返回更新后的完整供应商
 */
export function UpdateProvider(provider: $models.PiProvider): $CancellablePromise<$models.PiProvider> {
    return $Call.ByID(2275520661, provider).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $models.PiProvider.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType0);
const $$createType3 = $Create.Map($Create.Any, $Create.Any);
