// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CheckProviderQuota(kind: string, providerID: string): $CancellablePromise<$models.ProviderQuotaAutomationResult | null> {
    return $Call.ByID(777947223, kind, providerID).then(($result: any) => {
        return $$createType1($result);
    });
}

export function HandleSettingsChanged(previous: $models.AppSettings, next: $models.AppSettings): $CancellablePromise<void> {
    return $Call.ByID(1895188789, previous, next);
}

export function ResumeProviderQuotaAutomation(kind: string, providerID: string): $CancellablePromise<$models.ProviderQuotaAutomationResult | null> {
    return $Call.ByID(4291969609, kind, providerID).then(($result: any) => {
        return $$createType1($result);
    });
}

export function Start(): $CancellablePromise<void> {
    return $Call.ByID(3196978448);
}

export function Stop(): $CancellablePromise<void> {
    return $Call.ByID(2097562388);
}

export function TemporarilyEnableProvider(kind: string, providerID: string): $CancellablePromise<$models.ProviderQuotaAutomationResult | null> {
    return $Call.ByID(559787474, kind, providerID).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.ProviderQuotaAutomationResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
