// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function QueryQuota(queryType: string, apiURL: string, apiKey: string, queryConfig: $models.ProviderQuotaQueryConfig | null): $CancellablePromise<$models.ProviderQuotaQueryResult | null> {
    return $Call.ByID(2637189719, queryType, apiURL, apiKey, queryConfig).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ValidateScriptPreset(templateType: string, scriptCode: string): $CancellablePromise<$models.ProviderQuotaScriptValidationResult | null> {
    return $Call.ByID(2037877561, templateType, scriptCode).then(($result: any) => {
        return $$createType3($result);
    });
}

// Private type creation functions
const $$createType0 = $models.ProviderQuotaQueryResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.ProviderQuotaScriptValidationResult.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
