// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetConfig(): $CancellablePromise<$models.WebDAVSyncConfig> {
    return $Call.ByID(2635826082).then(($result: any) => {
        return $$createType0($result);
    });
}

export function LoadFromWebDAV(cfg: $models.WebDAVSyncConfig): $CancellablePromise<$models.WebDAVSyncResult> {
    return $Call.ByID(3411650357, cfg).then(($result: any) => {
        return $$createType1($result);
    });
}

export function PreviewLocalContent(): $CancellablePromise<$models.WebDAVSyncResult> {
    return $Call.ByID(2845957360).then(($result: any) => {
        return $$createType1($result);
    });
}

export function SaveConfig(cfg: $models.WebDAVSyncConfig): $CancellablePromise<$models.WebDAVSyncConfig> {
    return $Call.ByID(1507636567, cfg).then(($result: any) => {
        return $$createType0($result);
    });
}

export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(1721946003, app);
}

export function Start(): $CancellablePromise<void> {
    return $Call.ByID(3030319780);
}

export function Stop(): $CancellablePromise<void> {
    return $Call.ByID(382171808);
}

export function SyncToWebDAV(cfg: $models.WebDAVSyncConfig): $CancellablePromise<$models.WebDAVSyncResult> {
    return $Call.ByID(1418384539, cfg).then(($result: any) => {
        return $$createType1($result);
    });
}

export function TestConfig(cfg: $models.WebDAVSyncConfig): $CancellablePromise<$models.WebDAVTestResult> {
    return $Call.ByID(3353121418, cfg).then(($result: any) => {
        return $$createType2($result);
    });
}

// Private type creation functions
const $$createType0 = $models.WebDAVSyncConfig.createFrom;
const $$createType1 = $models.WebDAVSyncResult.createFrom;
const $$createType2 = $models.WebDAVTestResult.createFrom;
