// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * XaiOAuthService 管理 xAI 设备码登录与 access token 刷新。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetStatus 汇总当前登录状态
 */
export function GetStatus(): $CancellablePromise<$models.XaiOAuthStatus | null> {
    return $Call.ByID(2198698439).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetValidToken 返回有效 access token：缓存可用直接返回，否则按账号互斥刷新
 */
export function GetValidToken(accountID: string): $CancellablePromise<[string, string]> {
    return $Call.ByID(2936560590, accountID);
}

/**
 * ListAccounts 返回全部已登录账号
 */
export function ListAccounts(): $CancellablePromise<$models.XaiOAuthAccount[]> {
    return $Call.ByID(4032092103).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * Logout 清空全部账号与内存缓存
 */
export function Logout(): $CancellablePromise<void> {
    return $Call.ByID(87447781);
}

/**
 * PollLogin 轮询 token 端点换取凭据；授权未完成时返回可重试的哨兵错误
 */
export function PollLogin(deviceCode: string): $CancellablePromise<$models.XaiOAuthAccount | null> {
    return $Call.ByID(3547189687, deviceCode).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * RemoveAccount 移除指定账号并清理其内存缓存
 */
export function RemoveAccount(accountID: string): $CancellablePromise<void> {
    return $Call.ByID(3365751242, accountID);
}

/**
 * SetDefaultAccount 设置默认账号
 */
export function SetDefaultAccount(accountID: string): $CancellablePromise<void> {
    return $Call.ByID(1158083693, accountID);
}

export function Start(): $CancellablePromise<void> {
    return $Call.ByID(3537951329);
}

/**
 * StartLogin 发起设备码授权，返回前端展示用的用户码与校验地址
 */
export function StartLogin(): $CancellablePromise<$models.XaiOAuthDeviceCodeResponse | null> {
    return $Call.ByID(1049066422).then(($result: any) => {
        return $$createType6($result);
    });
}

export function Stop(): $CancellablePromise<void> {
    return $Call.ByID(2519232091);
}

// Private type creation functions
const $$createType0 = $models.XaiOAuthStatus.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.XaiOAuthAccount.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Nullable($$createType2);
const $$createType5 = $models.XaiOAuthDeviceCodeResponse.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
